version: "3.9"
services:
  postgres:
    image: postgres:13.4-alpine3.14
    environment:
      - POSTGRES_PASSWORD=qwerty
    ports:
      - 5432:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  web:
    build: ./python
    image: com.cobenagroup/web-demo:0.1.0
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PWD=qwerty
    ports:
      - 8080:8000
